import Head from "next/head";
import {
  ChevronRightSvg,
  FacebookSVG,
  InstagramSVG,
  LogoSVG,
  TwitterSVG,
} from "./Utils/Svgs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Modern Art Gallery</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <img
            src="/images/mobile/image-hero@2x.jpg"
            alt="people looking at a painting"
            className="max-h-[240px] md:hidden"
          />
        </div>
        <section className="mt-8 flex flex-col gap-8 px-3">
          <h1 className="text-[60px] font-[900] leading-[55px] text-[#151515]">
            MODERN
            <h1>ART GALLERY</h1>
          </h1>

          <div>
            <p className="text-lg font-light leading-[28px] text-[#444444]">
              The arts in the collection of the Modern Art Gallery all started
              from a spark of inspiration. Will these pieces inspire you? Visit
              us and find out.
            </p>
          </div>
          <div className="flex">
            <button className="h-[72px] w-[204px] bg-[#151515] text-xl font-extrabold leading-[23.94px] text-[#ffffff]">
              OUR LOCATION
            </button>
            <div className="flex h-[72px] w-[56px] items-center justify-center bg-[#d59663]">
              <ChevronRightSvg />
            </div>
          </div>
        </section>
        <section className="mt-[120px] px-4">
          <img src="/images/mobile/image-grid-1@2x.jpg" alt="art work" />
          <div className="mt-[25px] mb-[21px]">
            <h1 className="text-[50px] font-[900] leading-[45px]">
              YOUR DAY <br />
              AT THE GALLERY
            </h1>
          </div>
          <div className="mb-[32px]">
            <p className="text-lg font-light leading-[28px]">
              Wander through our distinct collections and find new insights
              about our artists. Dive into the details of their creative
              process.
            </p>
          </div>
          <div className="mb-[21px]">
            <img
              src="/images/mobile/image-grid-2@2x.jpg"
              alt="art work of a bench"
            />
          </div>
          <div className="mb-[16px]">
            <img
              src="/images/mobile/image-grid-3@2x.jpg"
              alt="people looking at art"
            />
          </div>
          <div className="h-[293px] bg-[#151515]">
            <div className="px-6 pt-12 pb-[47px]">
              <h1 className="mb-6 text-[50px] font-black leading-[45px] text-white">
                COME & BE <br />
                INSPIRED
              </h1>
              <p className="text-lg font-light leading-7 text-white">
                We’re excited to welcome you to our gallery and see how our
                collections influence you.
              </p>
            </div>
          </div>
        </section>
        <footer className="mt-[120px]">
          <div className="h-[336px] bg-[#151515]">
            <div className="py-12 px-8">
              <LogoSVG />
              <p className="py-[38px] text-base font-light leading-[26px] text-white">
                The Modern Art Gallery is free to all visitors and open seven
                days a week from 8am to 9pm. Find us at 99 King Street, Newport,
                USA.
              </p>
              <div className="flex gap-5">
                <FacebookSVG /> <InstagramSVG /> <TwitterSVG />
              </div>
            </div>
          </div>
        </footer>
      </main>
    </>
  );
}
